In [1]:
import geopandas as gpd
import pandas as pd
import os
import matplotlib as mpl
from matplotlib import cm

In [2]:
MPS_crime = pd.read_csv('MPS LSOA Level Crime (most recent 24 months).csv')
MPS_crime

,LSOA Code,LSOA Name,Borough,Major Category,Minor Category,202210,202211,202212,202301,202302,...,202312,202401,202402,202403,202404,202405,202406,202407,202408,202409
0,E01000006,Barking and Dagenham 016A,E09000002,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,0
1,E01000006,Barking and Dagenham 016A,E09000002,BURGLARY,BURGLARY - RESIDENTIAL,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,E01000006,Barking and Dagenham 016A,E09000002,BURGLARY,BURGLARY IN A DWELLING,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,E01000006,Barking and Dagenham 016A,E09000002,DRUG OFFENCES,POSSESSION OF DRUGS,4,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,E01000006,Barking and Dagenham 016A,E09000002,DRUG OFFENCES,TRAFFICKING OF DRUGS,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100376,E01035722,Westminster 024G,E09000033,THEFT,THEFT FROM THE PERSON,3,0,1,0,0,...,2,2,0,0,1,1,1,1,1,3
100377,E01035722,Westminster 024G,E09000033,VEHICLE OFFENCES,THEFT FROM A VEHICLE,1,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
100378,E01035722,Westminster 024G,E09000033,VEHICLE OFFENCES,THEFT OR UNAUTH TAKING OF A MOTOR VEH,1,0,0,0,1,...,1,0,0,1,2,1,0,1,0,0
100379,E01035722,Westminster 024G,E09000033,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY,1,2,0,3,0,...,0,1,1,1,0,1,2,0,0,0
100380,E01035722,Westminster 024G,E09000033,VIOLENCE AGAINST THE PERSON,VIOLENCE WITHOUT INJURY,3,2,2,2,0,...,3,2,3,2,1,2,3,2,2,0

In [3]:
bike_theft = MPS_crime[MPS_crime['Minor Category'] == 'BICYCLE THEFT'].reset_index(drop=True)
#bike_theft['total'] =  bike_theft.iloc[:, 6:].sum(axis=1)
#bike_theft = bike_theft.rename(columns={'LSOA Code':'lsoa21cd', '202409':'most_recent'})
#bike_theft_short = bike_theft[['lsoa21cd', 'most_recent', 'total']]
bike_theft_short = bike_theft.drop(columns=['Major Category', 'Minor Category'])
#bike_theft_short.to_csv('bike_theft.csv', index=False)

In [4]:
total = bike_theft_short.iloc[:, 3:].sum(axis=1)
#monthly = bike_theft_short.iloc[:, 3:].values.tolist()
bike_theft_compact = bike_theft_short#.iloc[:, :3]
#bike_theft_compact['Monthly'] = monthly
bike_theft_compact['Total'] = total
bike_theft_compact

,LSOA Code,LSOA Name,Borough,202210,202211,202212,202301,202302,202303,202304,...,202401,202402,202403,202404,202405,202406,202407,202408,202409,Total
0,E01000007,Barking and Dagenham 015A,E09000002,0,2,0,0,2,0,0,...,1,1,0,1,0,0,0,1,0,15
1,E01000009,Barking and Dagenham 016B,E09000002,1,0,0,1,0,0,0,...,1,0,0,0,0,1,0,0,0,5
2,E01000011,Barking and Dagenham 016C,E09000002,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,E01000012,Barking and Dagenham 015D,E09000002,0,0,0,1,0,0,2,...,0,0,1,0,0,1,0,0,0,5
4,E01000013,Barking and Dagenham 013A,E09000002,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3883,E01035718,Westminster 019G,E09000033,6,1,1,1,2,1,2,...,1,4,3,2,1,4,8,3,3,69
3884,E01035719,Westminster 021F,E09000033,0,0,1,1,0,1,0,...,0,0,0,0,1,0,0,0,0,6
3885,E01035720,Westminster 021G,E09000033,1,0,2,0,0,0,1,...,1,0,0,1,1,0,0,1,2,14
3886,E01035721,Westminster 023H,E09000033,1,1,0,0,1,1,0,...,0,1,2,1,0,0,1,0,1,18
3887,E01035722,Westminster 024G,E09000033,0,0,2,0,0,1,0,...,0,0,0,0,0,0,0,3,1,10

In [5]:
shape_files = [f for f in os.listdir('LB_shp/') if '.shp' in f]

dat_ls = []
for file in shape_files:
    temp = gpd.read_file(f'LB_shp/{file}')
    dat_ls.append(temp)

lsoa2021 = pd.concat(dat_ls)
lsoa2021.geometry = lsoa2021.geometry.to_crs(epsg=4326)
lsoa2021 = lsoa2021.reset_index(drop=True)

In [6]:
lsoa2021.geometry = lsoa2021.geometry.simplify(0.00001)

In [7]:
lsoa2021

,lsoa21cd,lsoa21nm,msoa21cd,msoa21nm,lad22cd,lad22nm,geometry
0,E01000011,Barking and Dagenham 016C,E02000017,Barking and Dagenham 016,E09000002,Barking and Dagenham,"POLYGON ((0.08391 51.54293, 0.08475 51.54249, ..."
1,E01000046,Barking and Dagenham 017D,E02000018,Barking and Dagenham 017,E09000002,Barking and Dagenham,"POLYGON ((0.12197 51.5391, 0.12211 51.53851, 0..."
2,E01000051,Barking and Dagenham 021D,E02000022,Barking and Dagenham 021,E09000002,Barking and Dagenham,"POLYGON ((0.08351 51.53552, 0.08375 51.53522, ..."
3,E01000077,Barking and Dagenham 008F,E02000009,Barking and Dagenham 008,E09000002,Barking and Dagenham,"POLYGON ((0.12655 51.548, 0.12615 51.54765, 0...."
4,E01000083,Barking and Dagenham 007F,E02000008,Barking and Dagenham 007,E09000002,Barking and Dagenham,"POLYGON ((0.13247 51.55556, 0.13242 51.55517, ..."
...,...,...,...,...,...,...,...
4989,E01004727,Westminster 008D,E02000967,Westminster 008,E09000033,Westminster,"POLYGON ((-0.1604 51.53599, -0.15965 51.53489,..."
4990,E01035716,Westminster 013G,E02000972,Westminster 013,E09000033,Westminster,"POLYGON ((-0.13702 51.51583, -0.13771 51.51575..."
4991,E01004731,Westminster 020A,E02000979,Westminster 020,E09000033,Westminster,"POLYGON ((-0.13707 51.5033, -0.13606 51.50239,..."
4992,E01004736,Westminster 018C,E02000977,Westminster 018,E09000033,Westminster,"POLYGON ((-0.13286 51.51119, -0.13285 51.51117..."
4993,E01035718,Westminster 019G,E02000978,Westminster 019,E09000033,Westminster,"POLYGON ((-0.15628 51.50999, -0.15484 51.50898..."

In [8]:
merged = lsoa2021.merge(bike_theft_compact, left_on='lsoa21cd', right_on='LSOA Code', how='left')
merged = merged.drop(columns=['LSOA Code', 'LSOA Name', 'msoa21cd', 'msoa21nm', 'Borough'])
merged = merged.rename(columns={'lsoa21cd':'LSOA Code', 'lsoa21nm':'LSOA Name', 'lad22cd':'Borough', 'lad22nm':'Borough Name'})
#merged = merged.fillna('No data')

#def assign_color_rgb(times):
 #   output_col = scalarMap.to_rgba(times)
  #  return f'rgb({int(output_col[0] * 255)}, {int(output_col[1] * 255)}, {int(output_col[2] * 255)})' 

#merged['color'] = merged['Total'].apply(assign_color_rgb)

merged

,LSOA Code,LSOA Name,Borough,Borough Name,geometry,202210,202211,202212,202301,202302,...,202401,202402,202403,202404,202405,202406,202407,202408,202409,Total
0,E01000011,Barking and Dagenham 016C,E09000002,Barking and Dagenham,"POLYGON ((0.08391 51.54293, 0.08475 51.54249, ...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,E01000046,Barking and Dagenham 017D,E09000002,Barking and Dagenham,"POLYGON ((0.12197 51.5391, 0.12211 51.53851, 0...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,E01000051,Barking and Dagenham 021D,E09000002,Barking and Dagenham,"POLYGON ((0.08351 51.53552, 0.08375 51.53522, ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E01000077,Barking and Dagenham 008F,E09000002,Barking and Dagenham,"POLYGON ((0.12655 51.548, 0.12615 51.54765, 0....",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,E01000083,Barking and Dagenham 007F,E09000002,Barking and Dagenham,"POLYGON ((0.13247 51.55556, 0.13242 51.55517, ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,E01004727,Westminster 008D,E09000033,Westminster,"POLYGON ((-0.1604 51.53599, -0.15965 51.53489,...",1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,11.0
4990,E01035716,Westminster 013G,E09000033,Westminster,"POLYGON ((-0.13702 51.51583, -0.13771 51.51575...",8.0,9.0,1.0,4.0,2.0,...,3.0,5.0,8.0,3.0,6.0,4.0,11.0,2.0,5.0,143.0
4991,E01004731,Westminster 020A,E09000033,Westminster,"POLYGON ((-0.13707 51.5033, -0.13606 51.50239,...",0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,4.0,28.0
4992,E01004736,Westminster 018C,E09000033,Westminster,"POLYGON ((-0.13286 51.51119, -0.13285 51.51117...",6.0,1.0,1.0,3.0,0.0,...,1.0,4.0,7.0,6.0,2.0,7.0,4.0,3.0,5.0,102.0
4993,E01035718,Westminster 019G,E09000033,Westminster,"POLYGON ((-0.15628 51.50999, -0.15484 51.50898...",6.0,1.0,1.0,1.0,2.0,...,1.0,4.0,3.0,2.0,1.0,4.0,8.0,3.0,3.0,69.0

In [14]:
merged.to_file('lsoa21.geojson', driver="GeoJSON")

## Plotting

In [9]:
import altair as alt
import datetime as dt

In [10]:
to_plot = merged.drop(columns=['geometry', 'Total'])

In [11]:
totals = to_plot.iloc[:,4:].sum().T

In [12]:
totals = pd.DataFrame(totals)

In [13]:
totals['Months'] = pd.to_datetime(totals.index.str[4:] + '-' + totals.index.str[0:4], format='%m-%Y')

In [14]:
totals = totals.rename(columns={0:'Total thefts'})

In [19]:
# Adapted from https://altair-viz.github.io/gallery/multiline_tooltip.html

def plot_theft_chart(totals):
    nearest = alt.selection_point(nearest=True, on="pointerover", fields=["Months"], empty=False)

    line = alt.Chart(totals).mark_line().encode(
        x=alt.Y('Months:T',
                scale=alt.Scale(domain=[dt.datetime(2022, 9, 1),dt.datetime(2024, 10, 1)]),
                axis=alt.Axis(format="%B %Y", tickCount=24, labelAngle=80),
               ),
        y=alt.X('Total thefts')
    )

    selectors = alt.Chart(totals).mark_point().encode(x='Months', opacity=alt.value(0)).add_params(nearest)
    
    when_near = alt.when(nearest)
    
    points = line.mark_point().encode(opacity=when_near.then(alt.value(1)).otherwise(alt.value(0)) )
    
    text = line.mark_text(align="left", dx=5, dy=-5).encode(text=when_near.then("Total thefts").otherwise(alt.value(" ")) )
    
    rules = alt.Chart(totals).mark_rule(color="gray").encode(x="Months").transform_filter(nearest)
    
    final_chart = alt.layer(line, selectors, points, rules, text).properties(width=600, height=300)

    return final_chart

In [20]:
total_chart = plot_theft_chart(totals)
total_chart.show()

alt.LayerChart(...)

In [111]:
total_chart.save('total_thefts.html')

In [124]:
for borough in to_plot['Borough Name'].unique():
    borough_plot = to_plot[to_plot['Borough Name'] == borough]
    borough_total = borough_plot.iloc[:,4:].sum().T
    borough_total = pd.DataFrame(borough_total)
    borough_total['Months'] = pd.to_datetime(borough_total.index.str[4:] + '-' + borough_total.index.str[0:4], format='%m-%Y')
    borough_total = borough_total.rename(columns={0:'Total thefts'})
    borough_chart = plot_theft_chart(borough_total)
    borough_chart.save('borough_charts/' + borough.replace(' ', '_') + '.html')